#!/usr/bin/env zsh

source "$SKETCHYBAR_CONFIG_DIR/colors.sh"
source "$SKETCHYBAR_CONFIG_DIR/icons.sh"
source "$SKETCHYBAR_CONFIG_DIR/settings.sh"
source "$SKETCHYBAR_CONFIG_DIR/utils.sh"

ITEM_DIR="$SKETCHYBAR_CONFIG_DIR/items"
PLUGIN_DIR="$SKETCHYBAR_CONFIG_DIR/plugins"
SCRIPT_DIR="$SKETCHYBAR_CONFIG_DIR/scripts"

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper 2>/dev/null || true
"$SKETCHYBAR_HELPER_BIN" "$HELPER" > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
if [[ -f /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist ]]; then
  launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &
fi

# Setting up the general bar appearance and default values
sketchybar --bar     height=43                                         \
                     color=$DIM                                        \
                     position=top                                      \
                     topmost=on                                        \
                     sticky=on                                         \
                     y_offset=0                                        \
                     notch_width=0                                     \
                     display=main                                      \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     padding_right=$PADDINGS                           \
                     padding_left=$PADDINGS                            \
                     background.height=30                              \
                     background.corner_radius=9                        \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=2                  \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=on

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/toggle_native_bar.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/aliases.sh"
source "$ITEM_DIR/task.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
