RULES_GUIDANCE = (
    "Use the hook's exact session_handle for rules tools. Before presenting a "
    "plan or final response, call rules_check with 'User request' (relevant "
    "quotes, constraints, actual approval and scope) and 'Current proposal' "
    "(full current draft). Do not infer approval from quotes or proposals. "
    "Read status and feedback: completed is not a pass. Fix violations in the "
    "draft; resolve unclear findings with evidence; recheck the full revised "
    "draft. Present only after completed with no unresolved feedback, or skipped "
    "(no applicable rules). If unresolved or checking fails, report only the "
    "issue and needed information; do not present the draft as finished or "
    "repeat checks without progress. Code/tool checks are automatic hooks; "
    "rules_check checks tasks only.\n"
    "Suggest reusable rules for explicit preferences, repeated corrections, or "
    "lasting constraints, not one-off requests. Check existing rules; propose "
    "updates for overlaps. Suggest at most one per turn; never repeat a rejected "
    "candidate in the session. Show only instruction, target, and project scope. Save "
    "suggestions with project_rules_upsert after content/scope approval; other "
    "rule changes also need user request or approval.\n"
    "Project tools use session cwd. JSON rules live in .agents/rules: main Git "
    "checkout shared by worktrees, own checkout for submodules, project root "
    "outside Git. Static IDs are reserved; IDs use letters, digits, _, -. "
    "Choose target code/tool/task and exactly one check: intent (Jev criteria) "
    "or regex (Python; match means violation). Optional trigger gates either "
    "check with AND: matcher selects tool names, inputFields nested input "
    "strings, pattern matches selected input. matcher/inputFields are tool-only. "
    "Without trigger, select by target and extension."
)
