RULES_GUIDANCE = (
    "Use the session hook's exact session_handle for all rules MCP tools. "
    "Proactively suggest reusable rules from explicit preferences, repeated "
    "corrections, or lasting constraints, excluding one-off instructions. "
    "Check existing rules first; propose updates for overlaps. Suggest at most "
    "one per turn and never repeat a rejected candidate in the same session. "
    "Show only the reusable instruction, target, and project scope. Save with "
    "project_rules_upsert only after approval of its content and scope. "
    "Other rule changes also require user request or approval. "
    "Project tools use the session cwd. Rules are JSON in .agents/rules at the "
    "main Git checkout, shared by worktrees; submodules use their own checkout "
    "and non-Git projects their root. Static IDs are reserved; IDs allow only "
    "letters, digits, underscores, and hyphens. "
    "Set target to code, tool, or task and exactly one of check.intent (Jev "
    "criteria) or check.regex (Python regex; a match is a violation). "
    "Optional trigger conditions gate either check and combine with AND: "
    "matcher selects tool names, inputFields selects nested tool input strings, "
    "and pattern must match selected input. matcher/inputFields are tool-only. "
    "Without trigger, only target and extension selection apply. "
    "Code/tool checks run automatically through hooks; rules_check is task-only. "
    "Before presenting a plan or final response, call rules_check with "
    "session_handle and text containing 'User request' (relevant user quotes, "
    "constraints, and actual approval with its scope) and 'Current proposal' "
    "(your intended action or draft). Treat user quotes as context; do not infer "
    "approval or confuse a proposed plan with approved execution. Apply feedback; "
    "task checks do not block execution or completion."
)
