RULES_GUIDANCE = (
    "Use the exact session_handle supplied by the session hook with the rules "
    "MCP tools: rules_list, rules_check, project_rules_upsert, project_rules_list, "
    "and project_rules_remove. "
    "Proactively suggest reusable rules from explicit user preferences, repeated "
    "corrections, and constraints that apply to future work. Exclude one-off task "
    "instructions and check existing rules before suggesting a candidate. If a "
    "candidate overlaps an existing rule, propose an update instead of a duplicate. "
    "Suggest at most one candidate per turn and do not repeat rejected candidates "
    "in the same session. Show the proposed rule text, target (code, tool, or task), "
    "and project scope. Extract only the reusable instruction, not the whole "
    "conversation. Save a suggested rule only after the user approves its content "
    "and project scope, using project_rules_upsert. Other rule changes also require "
    "a user request or approval. Static rule IDs are reserved. "
    "Project tools use the session's current working directory. Project rules are "
    "JSON files in .agents/rules under the Git repository's main checkout, shared "
    "by its worktrees. Submodules use their own checkout; non-Git projects use "
    "their project root. Rule IDs may contain only letters, digits, underscores, "
    "and hyphens. For rule definitions, specify target as code, tool, or task. "
    "Each rule requires exactly one of check.intent (Jev criteria) or check.regex "
    "(a Python regular expression whose match is a violation). Optional trigger "
    "conditions gate either check: matcher selects tool names, inputFields selects "
    "nested tool input strings, and pattern must match selected input. Tool name "
    "and input field selectors are only available for tool rules. Conditions are "
    "combined with AND; omit trigger to use only target and extension selection. "
    "Code and tool rules are checked automatically through hooks. "
    "Use rules_check only for task material, passing session_handle and text. "
    "Before presenting a plan, call rules_check and include "
    "the relevant user request, constraints, and draft plan in text. "
    "When checking approval-dependent actions, include the actual user approval "
    "message and the plan or scope it approved; never invent approval. "
    "Distinguish proposing an unapproved plan from executing a change. "
    "Before sending a final response, use rules_check with its draft as text, "
    "and apply the feedback. Task-check feedback does not block tool execution "
    "or completion."
)
