#!/usr/bin/env zsh -f

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    echo "Usage: $0 <target_file> [--stdout]"
    exit 1
fi

TARGET_FILE_PATH=$1
TARGET_FILE=$(basename $TARGET_FILE_PATH)
TARGET_DIR=$(dirname $TARGET_FILE_PATH)
OPTS=$2

PYSEN_VERSION=$(poetry run pysen --version)

tempfile="$TARGET_DIR/.tmp.${TARGET_FILE}"
trap "rm -f $tempfile" 0 1 2 3 15

cp $TARGET_FILE_PATH $tempfile

if [[ "$PYSEN_VERSION" =~ "could not find" ]]; then
    black $tempfile > /dev/null 2>&1
    isort $tempfile > /dev/null 2>&1
else
    export PYSEN_IGNORE_GIT=1
    poetry run pysen run_files format $tempfile > /dev/null 2>&1
fi

if [ "$OPTS" = "--stdout" ]; then
    cat $tempfile
else
    cat $tempfile > $TARGET_FILE_PATH
fi
