#!/bin/zsh

# Replace the home directory with ~ and split the path into an array using / as the delimiter
local -a path_parts
path_parts=("${(@s:/:)${PWD/#$HOME/~}}")

# Process each element
for i in {1..$#path_parts}; do
    # Skip the home directory (~), empty elements, and the last element
    if [[ $path_parts[i] != "~" ]] && [[ -n $path_parts[i] ]] && (( i < $#path_parts )); then
        # Abbreviate the element to the first three characters and add ' '
        path_parts[i]=${path_parts[i][1,3]}…
    fi
done

# Join the elements back into a string
local new_path="${(j:/:)path_parts}"
echo "$new_path"
