#!/usr/bin/env bash

log_path="/tmp/tmux_popup_log"

if [ ! -f "$log_path" ]; then
    touch $log_path
fi

buf=""

# if current project is child of git project, show git branch
is_git=$(git rev-parse --is-inside-work-tree)

if [[ $is_git == "true" ]]; then
    GIT_BRANCH=$(shorten-string 20 $(git branch --show-current))
    buf="#[fg=red]${GIT_BRANCH}#[fg=default]"
    buf="#[fg=grey]Git#[fg=default]($buf):"
fi

message=$(tail -1 $log_path)

PWD=$(shorten-pwd)
buf="${message} - ${buf}${PWD}"

tracking=$(timew | awk 'NR == 1 { print $2 }')
if [[ "$tracking" != "is" ]]; then
    tracking=" #[bg=black] #[fg=red]*#[fg=green][$tracking]#[fg=default bg=default]"
else
    tracking=""
fi

buf="${buf}${tracking}"


echo "${buf}"
