# Q pre block. Keep at the top of this file.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Created by `pipx` on 2023-04-13 09:31:33
export PATH="$PATH:/Users/jasony/.local/bin"

# Added by OrbStack: command-line tools and integration
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

# Q post block. Keep at the bottom of this file.
